# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7db6eaace4b3cec0fc3e1ad039a2ae160a2840c2f17184881f89c73d47850977d5a2845545131535006894e73adace335d38417aeabb44cca0a440fc6fc95fd

test:
  secret_key_base: 4cd04b253e6fc4e4102063c98cf239675054ceaa7e0c46340f1f1b8356212030113befd2b68cfcbf52ccdacf3ac2d83eb2bff45020d1eea428b59c2aaf9c7db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
